{% set name = "python-jose" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8255fb3cc524c04f4c790547a6215468f2a32d3a866424175523359e69f3aeb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - ecdsa <1.0
    - cryptography
    - future <1.0
    - python
    - six <2.0

test:
  imports:
    - jose
    - jose.backends

about:
  home: http://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://github.com/mpdavis/python-jose
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
