travis:
  secure:
    BINSTAR_TOKEN: QFx5wqygVwdExkUnW1Dn1UWTLm7x5cZpQOLe78pgGfjffVfzC87NPe2L+9DCuSTaXXI5Gg1iWRFbH+jRLVGCGLeUiUc/ZVVX7edU3cr9wrByg2bTGuHkyoke5M2o4daLBWE0ZF9BRSRRTAlDOf1iiHMr+ePhj9JaCBbAsU0B7NFZNYSfRtR/XuzF/QCY78Br2GCRi5GO9G2cfypvvHFz07OQBPY9zYdXC0gsxd+9qoOINPcMbbXdOSyoS3AtJSTM+Ie+g9RKOJUZG3C90QhJbGT4Elht9E/YrW7RgMszZid1UnL8yvPdePpQTNpYKfz6F3d4KQ7o2ewa52eDHALXdb6aJZUicgXPafV/m/G+7Y+RTr6rBmdVeP4zn+eBfdOm0DK17NcmeK6t1pxcbbEMXHed4+w3pq6YxuFYOlnHcS3Y/vUTEpc1AyPITdHv8K9GwAJz4i5zItptos1BE6WZU8RRLkUimL8WOB7lf+1WxpIVO1MEhCz9rOoYoW3x8zDhpipYKsjPyvmXCqdrpyj0tHR+S97KdGZtiLsBCypJp4j19wXx1y8ZDG+6vPbTkYs99Ipr8Mr9Ar3eKdX0CGsJ0xnzr52ydIqurf4Sjy9fyW7Ck59Mojo0Uil/UiPWtzgw3k+i5ZB9wcx5iXJCX2I45YYu5PhHjdq8zMG1SeUET4k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
